trigger:
  branches:
    include:
      - main

variables:
  azureServiceConnection: 'azure-connect'
  terraformDirectory: 'terraform-function-app/'

stages:
- stage: TerraformApply
  jobs:
  - job: apply
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    - script: |
        cd $(terraformDirectory)
        terraform init
        terraform apply -auto-approve
      displayName: 'Terraform Init and Apply'
