trigger:
- main

variables:
- group: Secrets  # Replace with the actual name of your variable group

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TerraformDeploy
  jobs:
  - job: DeployInfrastructure
    displayName: 'Terraform Init and Apply'
    steps:

    # Install Terraform
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'

    # Terraform Init
    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: './terraform-function-app'
        backendServiceArm: 'azure-connect'   # <-- this is required
    
    # Terraform Plan
    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: './terraform-function-app'

    # Terraform Apply
    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: './terraform-function-app'
        args: '-auto-approve'
